name: Deploy to ECS

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          echo "🔑 Logging in to Amazon ECR..."
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build, tag, and push image to ECR
        run: |
          set -e
          echo "🚀 Starting Docker build..."
          IMAGE_TAG=latest
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          echo "✅ Build finished, pushing to ECR..."
          docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "🎉 Image pushed to ECR successfully!"

      - name: Deploy to ECS
        run: |
          set -e
          echo "🚀 Starting ECS deployment..."
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment
          echo "🎉 ECS deployment completed!"
